// Captures documentation screenshots against a running, seeded server.
// Usage: PW_CHROMIUM_PATH=/path/to/chrome node scripts/screenshots.mjs
import { chromium } from "@playwright/test";
const base = process.env.E2E_BASE_URL ?? "http://localhost:3000";
const b = await chromium.launch(process.env.PW_CHROMIUM_PATH ? { executablePath: process.env.PW_CHROMIUM_PATH } : {});
const p = await b.newPage({ viewport: { width: 1360, height: 860 } });
await p.goto(`${base}/login`);
await p.getByLabel("Email").fill("admin@example.com");
await p.getByLabel("Password").fill("Admin12345!");
await p.getByRole("button", { name: "Sign in" }).click();
await p.waitForURL(`${base}/`);
await p.screenshot({ path: "docs/screenshots/dashboard.png" });
await p.goto(`${base}/companies`);
await p.screenshot({ path: "docs/screenshots/companies.png" });
const href = await p.getByRole("link", { name: "Northern Freight Solutions Ltd" }).getAttribute("href");
await p.goto(`${base}${href}`);
await p.screenshot({ path: "docs/screenshots/company-overview.png", fullPage: true });
await p.goto(`${base}/pipeline`);
await p.screenshot({ path: "docs/screenshots/pipeline-board.png" });
await p.goto(`${base}/contracts`);
await p.screenshot({ path: "docs/screenshots/contracts.png" });
await p.goto(`${base}/tasks`);
await p.screenshot({ path: "docs/screenshots/tasks.png" });
await p.goto(`${base}/finance`);
await p.screenshot({ path: "docs/screenshots/finance.png", fullPage: true });
await p.goto(`${base}/integrations/xero`);
await p.screenshot({ path: "docs/screenshots/integrations-xero.png", fullPage: true });
await p.goto(`${base}/devices`);
await p.screenshot({ path: "docs/screenshots/devices.png", fullPage: true });
await p.goto(`${base}/integrations/ninjaone`);
await p.screenshot({ path: "docs/screenshots/integrations-ninjaone.png", fullPage: true });
await p.goto(`${base}/integrations`);
await p.screenshot({ path: "docs/screenshots/integrations.png", fullPage: true });
await p.goto(`${base}/pipeline`);
await p.getByRole("link", { name: "Managed IT for 40 users + EDR" }).click();
await p.waitForURL(/\/pipeline\//);
await p.screenshot({ path: "docs/screenshots/opportunity-proposal.png", fullPage: true });
await b.close();
